import argparse
import json
import os
import shutil


def _safe_float(x, default=0.0):
    try:
        return float(x)
    except Exception:
        return float(default)


def _bbox_area(bbox):
    if not isinstance(bbox, list) or len(bbox) != 4:
        return 0
    try:
        _, _, w, h = [int(v) for v in bbox]
        return max(0, w) * max(0, h)
    except Exception:
        return 0


def _laplacian_var(img_path):
    try:
        import cv2
    except Exception:
        return None
    try:
        im = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
        if im is None:
            return None
        lap = cv2.Laplacian(im, cv2.CV_64F)
        return float(lap.var())
    except Exception:
        return None


def main():
    ap = argparse.ArgumentParser(description="Pick one representative face image for each person_id from face dump index.jsonl")
    ap.add_argument("--index", required=True, help="Path to index.jsonl generated by face dump")
    ap.add_argument("--out-dir", required=True, help="Output directory for per-person representative images")
    ap.add_argument("--min-area", type=int, default=40 * 40, help="Skip faces with bbox area below this threshold")
    ap.add_argument("--copy", action=argparse.BooleanOptionalAction, default=True, help="Copy images to out-dir (otherwise just write summary)")
    args = ap.parse_args()

    index_path = os.path.abspath(args.index)
    out_dir = os.path.abspath(args.out_dir)
    os.makedirs(out_dir, exist_ok=True)

    best = {}
    summary = []

    with open(index_path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                r = json.loads(line)
            except Exception:
                continue
            pid = r.get("person_id")
            face_path = r.get("face_path")
            bbox = r.get("bbox")
            if not (isinstance(pid, str) and pid):
                continue
            if not (isinstance(face_path, str) and face_path and os.path.exists(face_path)):
                continue
            area = _bbox_area(bbox)
            if area < int(args.min_area):
                continue
            sharp = _laplacian_var(face_path)
            key = (area, -1.0 if sharp is None else float(sharp))
            prev = best.get(pid)
            if prev is None or key > prev["key"]:
                best[pid] = {
                    "key": key,
                    "person_id": pid,
                    "face_path": os.path.abspath(face_path),
                    "t_sec": _safe_float(r.get("t_sec"), None),
                    "bbox": bbox,
                    "area": int(area),
                    "sharpness": sharp,
                }

    for pid, rec in sorted(best.items(), key=lambda kv: kv[0]):
        if args.copy:
            dst = os.path.join(out_dir, f"{pid}.jpg")
            try:
                shutil.copyfile(rec["face_path"], dst)
                rec["output_path"] = os.path.abspath(dst)
            except Exception:
                rec["output_path"] = None
        summary.append(rec)

    with open(os.path.join(out_dir, "summary.json"), "w", encoding="utf-8") as f:
        json.dump(
            {
                "index": index_path,
                "out_dir": out_dir,
                "total_person_ids": len(summary),
                "items": summary,
            },
            f,
            ensure_ascii=False,
            indent=2,
        )

    print(f"Done. person_ids={len(summary)} out_dir={out_dir}")


if __name__ == "__main__":
    main()

