import argparse
import json
import os
import random
from collections import defaultdict


def _read_index(index_path):
    items = []
    with open(index_path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                r = json.loads(line)
            except Exception:
                continue
            pid = r.get("person_id")
            face_path = r.get("face_path")
            if not (isinstance(pid, str) and pid):
                continue
            if not (isinstance(face_path, str) and face_path and os.path.exists(face_path)):
                continue
            items.append(r)
    return items


def _bbox_area(r):
    bbox = r.get("bbox")
    if not isinstance(bbox, list) or len(bbox) != 4:
        return 0
    try:
        _, _, w, h = [int(v) for v in bbox]
        return max(0, w) * max(0, h)
    except Exception:
        return 0


def _safe_float(x, default=None):
    try:
        return float(x)
    except Exception:
        return default


def _laplacian_var(cv2, img):
    try:
        gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        lap = cv2.Laplacian(gray, cv2.CV_64F)
        return float(lap.var())
    except Exception:
        return None


def _pick_diverse(records, k, rng, time_bin_sec=60.0):
    by_bin = defaultdict(list)
    for r in records:
        t = _safe_float(r.get("t_sec"), None)
        b = int(t // time_bin_sec) if isinstance(t, (int, float)) else -1
        by_bin[b].append(r)
    bins = list(by_bin.keys())
    rng.shuffle(bins)
    picked = []
    for b in bins:
        if len(picked) >= k:
            break
        rs = by_bin[b]
        rs.sort(key=lambda x: x.get("_rank_key", (0, 0)), reverse=True)
        picked.append(rs[0])
    if len(picked) < k:
        rest = [r for r in records if r not in picked]
        rest.sort(key=lambda x: x.get("_rank_key", (0, 0)), reverse=True)
        picked.extend(rest[: max(0, k - len(picked))])
    return picked[:k]


def _make_grid(cv2, tiles, cols, tile_w, tile_h, pad, header_h, title):
    rows = (len(tiles) + cols - 1) // cols
    w = cols * tile_w + (cols + 1) * pad
    h = rows * tile_h + (rows + 1) * pad + header_h
    import numpy as np

    canvas = np.full((h, w, 3), 255, dtype="uint8")

    if title:
        cv2.putText(canvas, title, (pad, int(header_h * 0.7)), cv2.FONT_HERSHEY_SIMPLEX, 1.0, (30, 30, 30), 2)

    for idx, t in enumerate(tiles):
        r = idx // cols
        c = idx % cols
        x0 = pad + c * (tile_w + pad)
        y0 = header_h + pad + r * (tile_h + pad)
        img = t.get("_img")
        if img is None:
            continue
        thumb = cv2.resize(img, (tile_w, tile_h))
        canvas[y0 : y0 + tile_h, x0 : x0 + tile_w] = thumb
        label = t.get("_label") or ""
        if label:
            cv2.rectangle(canvas, (x0, y0), (x0 + tile_w, y0 + 22), (0, 0, 0), -1)
            cv2.putText(canvas, label, (x0 + 6, y0 + 16), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (255, 255, 255), 1)
    return canvas


def main():
    ap = argparse.ArgumentParser(description="Create montage images per person_id for visual inspection.")
    ap.add_argument("--index", required=True, help="Path to index.jsonl generated by face dump")
    ap.add_argument("--out-dir", required=True, help="Output directory for montages")
    ap.add_argument("--max-pids", type=int, default=0, help="Only generate for top-N frequent pids (0 means all)")
    ap.add_argument(
        "--include-unknown",
        action=argparse.BooleanOptionalAction,
        default=False,
        help="Include unknown ids like u000123 in montages.",
    )
    ap.add_argument("--tiles", type=int, default=16, help="How many faces to show per pid montage")
    ap.add_argument("--cols", type=int, default=4, help="Grid columns")
    ap.add_argument("--tile-size", default="160x160", help="Tile size, e.g. 160x160")
    ap.add_argument("--seed", type=int, default=7)
    args = ap.parse_args()

    try:
        import cv2
    except Exception as e:
        raise SystemExit(f"cv2 is required: {e}")

    tile_w, tile_h = [int(x) for x in str(args.tile_size).lower().split("x", 1)]
    rng = random.Random(int(args.seed))

    items = _read_index(os.path.abspath(args.index))
    by_pid = defaultdict(list)
    for r in items:
        pid = r["person_id"]
        if not args.include_unknown and isinstance(pid, str) and pid.startswith("u"):
            continue
        by_pid[pid].append(r)

    pids = list(by_pid.keys())
    pids.sort(key=lambda p: len(by_pid[p]), reverse=True)
    if int(args.max_pids) > 0:
        pids = pids[: int(args.max_pids)]

    out_dir = os.path.abspath(args.out_dir)
    os.makedirs(out_dir, exist_ok=True)

    manifest = []
    for pid in pids:
        recs = by_pid[pid]
        enriched = []
        for r in recs:
            img = cv2.imread(r["face_path"])
            if img is None:
                continue
            area = _bbox_area(r)
            sharp = _laplacian_var(cv2, img)
            rk = (int(area), -1.0 if sharp is None else float(sharp))
            t = _safe_float(r.get("t_sec"), None)
            score = r.get("score")
            r2 = dict(r)
            r2["_img"] = img
            r2["_rank_key"] = rk
            if isinstance(score, (int, float)):
                lab = f"{pid} {float(score):.2f}"
            else:
                lab = pid
            if isinstance(t, (int, float)):
                lab = f"{lab} @{t:.0f}s"
            r2["_label"] = lab
            enriched.append(r2)

        if not enriched:
            continue

        enriched.sort(key=lambda x: x.get("_rank_key", (0, 0)), reverse=True)
        picked = _pick_diverse(enriched, int(args.tiles), rng=rng, time_bin_sec=90.0)
        grid = _make_grid(
            cv2=cv2,
            tiles=picked,
            cols=int(args.cols),
            tile_w=tile_w,
            tile_h=tile_h,
            pad=10,
            header_h=54,
            title=f"{pid}  n={len(enriched)}",
        )
        out_path = os.path.join(out_dir, f"{pid}.jpg")
        cv2.imwrite(out_path, grid)
        manifest.append({"person_id": pid, "count": len(enriched), "montage": os.path.abspath(out_path)})

    with open(os.path.join(out_dir, "manifest.json"), "w", encoding="utf-8") as f:
        json.dump({"index": os.path.abspath(args.index), "out_dir": out_dir, "items": manifest}, f, ensure_ascii=False, indent=2)

    print(f"Done. pids={len(manifest)} out_dir={out_dir}")


if __name__ == "__main__":
    main()
